In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.layers import Layer

In [3]:
df = pd.read_csv("Heart_disease_statlog.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0

In [4]:
df=df.dropna()
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.drop("target", axis=1), df["target"], test_size=0.2, random_state=42)

In [7]:
tf.keras.utils.set_random_seed(42)

nn_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.Dense(16, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

In [8]:
nn_model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss = tf.keras.losses.BinaryCrossentropy(),
    metrics=[                  
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.AUC(name="auc")
    ]
)

history = nn_model.fit(
    X_train,
    y_train,
    epochs=100,
    #class_weight=class_weights,
)

history_df = pd.DataFrame(history.history)
print("Epochs run:", len(history_df))
history_df.tail()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.3935 - auc: 0.3729 - loss: 5.5664 - precision: 0.4000 - recall: 0.6465
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5324 - auc: 0.4025 - loss: 3.4128 - precision: 0.4444 - recall: 0.0808
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4028 - auc: 0.4045 - loss: 2.0243 - precision: 0.4062 - recall: 0.6566
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5139 - auc: 0.4597 - loss: 1.4142 - precision: 0.4444 - recall: 0.2424
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5787 - auc: 0.5941 - loss: 1.1073 - precision: 0.5308 - recall: 0.6970
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5787 - auc: 0.6027 - loss: 1.0195 - precision: 0.5426 - recall: 0.5152
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5787 - auc: 0.6359 - loss: 0.8936 - precision: 0.5345 - recall: 0.6263
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5972 - auc: 0.6400 - loss: 0.8231 - precision: 0.5625 - recall: 0.5455
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6019 - auc: 0.6630 - loss: 0.7518 - precision: 0.5586 - recall: 0.6263
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6343 - auc: 0.6869 - loss: 0.7056 - precision: 0.6020 - recall: 0.5960
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6481 - auc: 0.7034 - loss: 0.6769 - precision: 0.6117 - recall: 0.6364
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6574 - auc: 0.7305 - loss: 0.6373 - precision: 0.6214 - recall: 0.6465
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6806 - auc: 0.7440 - loss: 0.6168 - precision: 0.6531 - recall: 0.6465
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6898 - auc: 0.7539 - loss: 0.6050 - precision: 0.6600 - recall: 0.6667
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7037 - auc: 0.7676 - loss: 0.5876 - precision: 0.6733 - recall: 0.6869
Epoch 16/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7130 - auc: 0.7786 - loss: 0.5724 - precision: 0.6947 - recall: 0.6667
Epoch 17/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7176 - auc: 0.7847 - loss: 0.5645 - precision: 0.7021 - recall: 0.6667
Epoch 18/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7269 - auc: 0.7922 - loss: 0.5562 - precision: 0.7083 - recall: 0.6869
Epoch 19/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7222 - auc: 0.7977 - loss: 0.5455 - precision: 0.7053 - recall: 0.6768
Epoch 20/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7315 - auc: 0.8044 - loss: 0.5369 - precision: 0.7158 - recall: 0.6869
Epoch 21/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7407 - auc: 0.8093 - loss: 0.5302 - precision: 0.7312 - recall: 0.6869
Epoch 22/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7361 - auc: 0.8143 - loss: 0.5238 - precision: 0.7283 - recall: 0.6768
Epoch 23/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7407 - auc: 0.8188 - loss: 0.5174 - precision: 0.7312 - recall: 0.6869
Epoch 24/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7407 - auc: 0.8238 - loss: 0.5112 - precision: 0.7312 - recall: 0.6869
Epoch 25/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7546 - auc: 0.8279 - loss: 0.5052 - precision: 0.7500 - recall: 0.6970
Epoch 26/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7546 - auc: 0.8323 - loss: 0.4995 - precision: 0.7500 - recall: 0.6970
Epoch 27/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7593 - auc: 0.8351 - loss: 0.4952 - precision: 0.7582 - recall: 0.6970
Epoch 28/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7778 - auc: 0.8398 - loss: 0.4909 - precision: 0.7742 - recall: 0.7273
Epoch 29/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7824 - auc: 0.8433 - loss: 0.4856 - precision: 0.7766 - recall: 0.7374
Epoch 30/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7824 - auc: 0.8465 - loss: 0.4817 - precision: 0.7766 - recall: 0.7374
Epoch 31/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7824 - auc: 0.8491 - loss: 0.4785 - precision: 0.7766 - recall: 0.7374
Epoch 32/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7824 - auc: 0.8524 - loss: 0.4742 - precision: 0.7766 - recall: 0.7374
Epoch 33/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7870 - auc: 0.8560 - loss: 0.4699 - precision: 0.7849 - recall: 0.7374
Epoch 34/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7870 - auc: 0.8574 - loss: 0.4671 - precision: 0.7849 - recall: 0.7374
Epoch 35/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7870 - auc: 0.8599 - loss: 0.4651 - precision: 0.7849 - recall: 0.7374
Epoch 36/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7917 - auc: 0.8626 - loss: 0.4614 - precision: 0.7935 - recall: 0.7374
Epoch 37/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7870 - auc: 0.8646 - loss: 0.4579 - precision: 0.7912 - recall: 0.7273
Epoch 38/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7917 - auc: 0.8662 - loss: 0.4555 - precision: 0.8000 - recall: 0.7273
Epoch 39/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7963 - auc: 0.8680 - loss: 0.4525 - precision: 0.8090 - recall: 0.7273
Epoch 40/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7963 - auc: 0.8689 - loss: 0.4521 - precision: 0.8090 - recall: 0.7273
Epoch 41/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8056 - auc: 0.8698 - loss: 0.4492 - precision: 0.8132 - recall: 0.7475
Epoch 42/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8194 - auc: 0.8724 - loss: 0.4456 - precision: 0.8409 - recall: 0.7475
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8102 - auc: 0.8737 - loss: 0.4424 - precision: 0.8295 - recall: 0.7374
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8102 - auc: 0.8746 - loss: 0.4406 - precision: 0.8295 - recall: 0.7374
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8102 - auc: 0.8772 - loss: 0.4382 - precision: 0.8295 - recall: 0.7374
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8148 - auc: 0.8791 - loss: 0.4355 - precision: 0.8315 - recall: 0.7475
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8148 - auc: 0.8798 - loss: 0.4338 - precision: 0.8315 - recall: 0.7475
Epoch 48/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8194 - auc: 0.8803 - loss: 0.4326 - precision: 0.8409 - recall: 0.7475
Epoch 49/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8194 - auc: 0.8824 - loss: 0.4305 - precision: 0.8409 - recall: 0.7475
Epoch 50/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8241 - auc: 0.8841 - loss: 0.4281 - precision: 0.8427 - recall: 0.7576
Epoch 51/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8241 - auc: 0.8847 - loss: 0.4268 - precision: 0.8427 - recall: 0.7576
Epoch 52/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8287 - auc: 0.8854 - loss: 0.4251 - precision: 0.8444 - recall: 0.7677
Epoch 53/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8241 - auc: 0.8868 - loss: 0.4228 - precision: 0.8352 - recall: 0.7677
Epoch 54/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8241 - auc: 0.8876 - loss: 0.4214 - precision: 0.8352 - recall: 0.7677
Epoch 55/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8241 - auc: 0.8877 - loss: 0.4203 - precision: 0.8352 - recall: 0.7677
Epoch 56/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8287 - auc: 0.8882 - loss: 0.4188 - precision: 0.8370 - recall: 0.7778
Epoch 57/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8287 - auc: 0.8896 - loss: 0.4166 - precision: 0.8370 - recall: 0.7778
Epoch 58/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8241 - auc: 0.8899 - loss: 0.4155 - precision: 0.8352 - recall: 0.7677
Epoch 59/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8241 - auc: 0.8899 - loss: 0.4145 - precision: 0.8352 - recall: 0.7677
Epoch 60/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8241 - auc: 0.8907 - loss: 0.4130 - precision: 0.8352 - recall: 0.7677
Epoch 61/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8287 - auc: 0.8911 - loss: 0.4116 - precision: 0.8370 - recall: 0.7778
Epoch 62/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8287 - auc: 0.8915 - loss: 0.4106 - precision: 0.8370 - recall: 0.7778
Epoch 63/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8287 - auc: 0.8920 - loss: 0.4094 - precision: 0.8370 - recall: 0.7778
Epoch 64/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - auc: 0.8932 - loss: 0.4081 - precision: 0.8539 - recall: 0.7677
Epoch 65/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8380 - auc: 0.8933 - loss: 0.4075 - precision: 0.8556 - recall: 0.7778
Epoch 66/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8426 - auc: 0.8941 - loss: 0.4067 - precision: 0.8571 - recall: 0.7879
Epoch 67/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8426 - auc: 0.8941 - loss: 0.4052 - precision: 0.8571 - recall: 0.7879
Epoch 68/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8380 - auc: 0.8948 - loss: 0.4039 - precision: 0.8556 - recall: 0.7778
Epoch 69/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8380 - auc: 0.8950 - loss: 0.4035 - precision: 0.8556 - recall: 0.7778
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8426 - auc: 0.8954 - loss: 0.4030 - precision: 0.8571 - recall: 0.7879
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8426 - auc: 0.8958 - loss: 0.4021 - precision: 0.8571 - recall: 0.7879
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8426 - auc: 0.8961 - loss: 0.4007 - precision: 0.8571 - recall: 0.7879
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8472 - auc: 0.8961 - loss: 0.4002 - precision: 0.8587 - recall: 0.7980
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.8965 - loss: 0.3998 - precision: 0.8587 - recall: 0.7980
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8472 - auc: 0.8968 - loss: 0.3989 - precision: 0.8587 - recall: 0.7980
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8472 - auc: 0.8975 - loss: 0.3978 - precision: 0.8587 - recall: 0.7980
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.8979 - loss: 0.3975 - precision: 0.8587 - recall: 0.7980
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8472 - auc: 0.8978 - loss: 0.3970 - precision: 0.8587 - recall: 0.7980
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.8978 - loss: 0.3964 - precision: 0.8587 - recall: 0.7980
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8472 - auc: 0.8980 - loss: 0.3956 - precision: 0.8587 - recall: 0.7980
Epoch 81/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.8988 - loss: 0.3947 - precision: 0.8587 - recall: 0.7980
Epoch 82/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8472 - auc: 0.8986 - loss: 0.3945 - precision: 0.8587 - recall: 0.7980
Epoch 83/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8472 - auc: 0.8986 - loss: 0.3942 - precision: 0.8587 - recall: 0.7980
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8472 - auc: 0.8989 - loss: 0.3937 - precision: 0.8587 - recall: 0.7980
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8472 - auc: 0.8992 - loss: 0.3929 - precision: 0.8587 - recall: 0.7980
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8472 - auc: 0.8994 - loss: 0.3923 - precision: 0.8587 - recall: 0.7980
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8472 - auc: 0.8995 - loss: 0.3921 - precision: 0.8587 - recall: 0.7980
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8472 - auc: 0.8993 - loss: 0.3919 - precision: 0.8587 - recall: 0.7980
Epoch 89/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.8993 - loss: 0.3914 - precision: 0.8587 - recall: 0.7980
Epoch 90/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8472 - auc: 0.8991 - loss: 0.3908 - precision: 0.8587 - recall: 0.7980
Epoch 91/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8472 - auc: 0.8998 - loss: 0.3902 - precision: 0.8587 - recall: 0.7980
Epoch 92/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8472 - auc: 0.9001 - loss: 0.3898 - precision: 0.8587 - recall: 0.7980
Epoch 93/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8472 - auc: 0.8998 - loss: 0.3899 - precision: 0.8587 - recall: 0.7980
Epoch 94/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8472 - auc: 0.8996 - loss: 0.3897 - precision: 0.8587 - recall: 0.7980
Epoch 95/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8472 - auc: 0.9002 - loss: 0.3893 - precision: 0.8587 - recall: 0.7980
Epoch 96/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8472 - auc: 0.9006 - loss: 0.3884 - precision: 0.8587 - recall: 0.7980
Epoch 97/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8472 - auc: 0.9008 - loss: 0.3879 - precision: 0.8587 - recall: 0.7980
Epoch 98/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.9011 - loss: 0.3880 - precision: 0.8587 - recall: 0.7980
Epoch 99/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.9014 - loss: 0.3879 - precision: 0.8587 - recall: 0.7980
Epoch 100/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8472 - auc: 0.9014 - loss: 0.3873 - precision: 0.8587 - recall: 0.7980
Epochs run: 100

    accuracy       auc      loss  precision   recall
95  0.847222  0.900587  0.388447   0.858696  0.79798
96  0.847222  0.900803  0.387875   0.858696  0.79798
97  0.847222  0.901062  0.387955   0.858696  0.79798
98  0.847222  0.901407  0.387906   0.858696  0.79798
99  0.847222  0.901364  0.387313   0.858696  0.79798

In [9]:
class TrigonometricExpansion(Layer):
    def call(self, x):
        return tf.concat([x, tf.sin(x), tf.cos(x)], axis=-1)

In [20]:
tf.keras.utils.set_random_seed(42)

nn_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    TrigonometricExpansion(),
    TrigonometricExpansion(),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

In [21]:
nn_model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-2),
    loss = tf.keras.losses.BinaryCrossentropy(),
    metrics=[                  
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.AUC(name="auc")
    ]
)

history = nn_model.fit(
    X_train,
    y_train,
    epochs=100,
    #class_weight=class_weights,
)

history_df = pd.DataFrame(history.history)
print("Epochs run:", len(history_df))
history_df.tail()

Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.4954 - auc: 0.4995 - loss: 16.7392 - precision: 0.4219 - recall: 0.2727
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4954 - auc: 0.5338 - loss: 6.8396 - precision: 0.4684 - recall: 0.7475
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6574 - auc: 0.6674 - loss: 2.6473 - precision: 0.6344 - recall: 0.5960
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7315 - auc: 0.7964 - loss: 1.4190 - precision: 0.7887 - recall: 0.5657
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8056 - auc: 0.8778 - loss: 0.9980 - precision: 0.7317 - recall: 0.9091
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8333 - auc: 0.9117 - loss: 0.6518 - precision: 0.8539 - recall: 0.7677
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8194 - auc: 0.8846 - loss: 0.7681 - precision: 0.7941 - recall: 0.8182
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8611 - auc: 0.9206 - loss: 0.4994 - precision: 0.8224 - recall: 0.8889
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - auc: 0.9363 - loss: 0.4351 - precision: 0.9011 - recall: 0.8283
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8704 - auc: 0.9264 - loss: 0.4731 - precision: 0.8737 - recall: 0.8384
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8657 - auc: 0.9307 - loss: 0.4262 - precision: 0.8431 - recall: 0.8687
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - auc: 0.9387 - loss: 0.3757 - precision: 0.8614 - recall: 0.8788
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8704 - auc: 0.9369 - loss: 0.3674 - precision: 0.8586 - recall: 0.8586
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8657 - auc: 0.9337 - loss: 0.3829 - precision: 0.8571 - recall: 0.8485
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8426 - auc: 0.9251 - loss: 0.4070 - precision: 0.8283 - recall: 0.8283
Epoch 16/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8333 - auc: 0.9161 - loss: 0.4369 - precision: 0.8119 - recall: 0.8283
Epoch 17/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8287 - auc: 0.9083 - loss: 0.4687 - precision: 0.8100 - recall: 0.8182
Epoch 18/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8056 - auc: 0.8978 - loss: 0.5013 - precision: 0.7938 - recall: 0.7778
Epoch 19/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7963 - auc: 0.8903 - loss: 0.5396 - precision: 0.7835 - recall: 0.7677
Epoch 20/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7824 - auc: 0.8801 - loss: 0.5927 - precision: 0.7653 - recall: 0.7576
Epoch 21/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7778 - auc: 0.8723 - loss: 0.6606 - precision: 0.7629 - recall: 0.7475
Epoch 22/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7824 - auc: 0.8631 - loss: 0.7254 - precision: 0.7600 - recall: 0.7677
Epoch 23/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7917 - auc: 0.8739 - loss: 0.7045 - precision: 0.7700 - recall: 0.7778
Epoch 24/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8241 - auc: 0.9023 - loss: 0.5592 - precision: 0.7905 - recall: 0.8384
Epoch 25/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8750 - auc: 0.9383 - loss: 0.4063 - precision: 0.8396 - recall: 0.8990
Epoch 26/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8750 - auc: 0.9456 - loss: 0.3534 - precision: 0.8600 - recall: 0.8687
Epoch 27/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8611 - auc: 0.9478 - loss: 0.3305 - precision: 0.8485 - recall: 0.8485
Epoch 28/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8796 - auc: 0.9472 - loss: 0.3219 - precision: 0.8763 - recall: 0.8586
Epoch 29/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8935 - auc: 0.9456 - loss: 0.3233 - precision: 0.8958 - recall: 0.8687
Epoch 30/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8704 - auc: 0.9402 - loss: 0.3413 - precision: 0.8586 - recall: 0.8586
Epoch 31/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8519 - auc: 0.9286 - loss: 0.3790 - precision: 0.8317 - recall: 0.8485
Epoch 32/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8380 - auc: 0.9151 - loss: 0.4176 - precision: 0.8200 - recall: 0.8283
Epoch 33/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8194 - auc: 0.9085 - loss: 0.4497 - precision: 0.8125 - recall: 0.7879
Epoch 34/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8148 - auc: 0.9040 - loss: 0.4782 - precision: 0.8041 - recall: 0.7879
Epoch 35/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8009 - auc: 0.8907 - loss: 0.5443 - precision: 0.7979 - recall: 0.7576
Epoch 36/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7685 - auc: 0.8766 - loss: 0.6246 - precision: 0.7579 - recall: 0.7273
Epoch 37/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7778 - auc: 0.8652 - loss: 0.7243 - precision: 0.7629 - recall: 0.7475
Epoch 38/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7917 - auc: 0.8738 - loss: 0.7170 - precision: 0.7547 - recall: 0.8081
Epoch 39/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8472 - auc: 0.9218 - loss: 0.4594 - precision: 0.8173 - recall: 0.8586
Epoch 40/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8843 - auc: 0.9433 - loss: 0.3615 - precision: 0.8627 - recall: 0.8889
Epoch 41/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8657 - auc: 0.9440 - loss: 0.3465 - precision: 0.8646 - recall: 0.8384
Epoch 42/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - auc: 0.9493 - loss: 0.3267 - precision: 0.8750 - recall: 0.8485
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8981 - auc: 0.9463 - loss: 0.3275 - precision: 0.8969 - recall: 0.8788
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8704 - auc: 0.9401 - loss: 0.3510 - precision: 0.8586 - recall: 0.8586
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8426 - auc: 0.9298 - loss: 0.3778 - precision: 0.8283 - recall: 0.8283
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8519 - auc: 0.9264 - loss: 0.3810 - precision: 0.8317 - recall: 0.8485
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8565 - auc: 0.9265 - loss: 0.3767 - precision: 0.8333 - recall: 0.8586
Epoch 48/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8380 - auc: 0.9297 - loss: 0.3716 - precision: 0.8200 - recall: 0.8283
Epoch 49/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8611 - auc: 0.9364 - loss: 0.3468 - precision: 0.8485 - recall: 0.8485
Epoch 50/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8611 - auc: 0.9405 - loss: 0.3309 - precision: 0.8416 - recall: 0.8586
Epoch 51/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8611 - auc: 0.9438 - loss: 0.3132 - precision: 0.8350 - recall: 0.8687
Epoch 52/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - auc: 0.9506 - loss: 0.2953 - precision: 0.8713 - recall: 0.8889
Epoch 53/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - auc: 0.9528 - loss: 0.2810 - precision: 0.8713 - recall: 0.8889
Epoch 54/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - auc: 0.9571 - loss: 0.2669 - precision: 0.8788 - recall: 0.8788
Epoch 55/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - auc: 0.9584 - loss: 0.2607 - precision: 0.8866 - recall: 0.8687
Epoch 56/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9028 - auc: 0.9586 - loss: 0.2589 - precision: 0.9062 - recall: 0.8788
Epoch 57/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9028 - auc: 0.9585 - loss: 0.2562 - precision: 0.9062 - recall: 0.8788
Epoch 58/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8889 - auc: 0.9590 - loss: 0.2557 - precision: 0.8866 - recall: 0.8687
Epoch 59/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8981 - auc: 0.9574 - loss: 0.2568 - precision: 0.8969 - recall: 0.8788
Epoch 60/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8981 - auc: 0.9568 - loss: 0.2594 - precision: 0.8969 - recall: 0.8788
Epoch 61/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9028 - auc: 0.9574 - loss: 0.2597 - precision: 0.8980 - recall: 0.8889
Epoch 62/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9074 - auc: 0.9549 - loss: 0.2680 - precision: 0.9072 - recall: 0.8889
Epoch 63/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8981 - auc: 0.9537 - loss: 0.2752 - precision: 0.8889 - recall: 0.8889
Epoch 64/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9028 - auc: 0.9515 - loss: 0.2789 - precision: 0.9062 - recall: 0.8788
Epoch 65/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9028 - auc: 0.9504 - loss: 0.2841 - precision: 0.9062 - recall: 0.8788
Epoch 66/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8981 - auc: 0.9471 - loss: 0.2931 - precision: 0.9053 - recall: 0.8687
Epoch 67/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8843 - auc: 0.9442 - loss: 0.3080 - precision: 0.8776 - recall: 0.8687
Epoch 68/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8796 - auc: 0.9407 - loss: 0.3244 - precision: 0.8925 - recall: 0.8384
Epoch 69/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8472 - auc: 0.9322 - loss: 0.3432 - precision: 0.8367 - recall: 0.8283
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8519 - auc: 0.9305 - loss: 0.3621 - precision: 0.8526 - recall: 0.8182
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8056 - auc: 0.9168 - loss: 0.4103 - precision: 0.7879 - recall: 0.7879
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8056 - auc: 0.9110 - loss: 0.4310 - precision: 0.7938 - recall: 0.7778
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8148 - auc: 0.9000 - loss: 0.4888 - precision: 0.8041 - recall: 0.7879
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7963 - auc: 0.8863 - loss: 0.5869 - precision: 0.7723 - recall: 0.7879
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8426 - auc: 0.9169 - loss: 0.4632 - precision: 0.8218 - recall: 0.8384
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8611 - auc: 0.9441 - loss: 0.3302 - precision: 0.8485 - recall: 0.8485
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8935 - auc: 0.9584 - loss: 0.2723 - precision: 0.8654 - recall: 0.9091
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8843 - auc: 0.9599 - loss: 0.2633 - precision: 0.8776 - recall: 0.8687
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9028 - auc: 0.9606 - loss: 0.2598 - precision: 0.8980 - recall: 0.8889
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9028 - auc: 0.9620 - loss: 0.2542 - precision: 0.9062 - recall: 0.8788
Epoch 81/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8935 - auc: 0.9625 - loss: 0.2462 - precision: 0.8878 - recall: 0.8788
Epoch 82/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9074 - auc: 0.9611 - loss: 0.2484 - precision: 0.9158 - recall: 0.8788
Epoch 83/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9074 - auc: 0.9576 - loss: 0.2645 - precision: 0.9158 - recall: 0.8788
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8935 - auc: 0.9490 - loss: 0.2884 - precision: 0.8958 - recall: 0.8687
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8704 - auc: 0.9408 - loss: 0.3149 - precision: 0.8515 - recall: 0.8687
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8519 - auc: 0.9343 - loss: 0.3375 - precision: 0.8317 - recall: 0.8485
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8194 - auc: 0.9307 - loss: 0.3581 - precision: 0.8125 - recall: 0.7879
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - auc: 0.9278 - loss: 0.3729 - precision: 0.8247 - recall: 0.8081
Epoch 89/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8472 - auc: 0.9308 - loss: 0.3661 - precision: 0.8300 - recall: 0.8384
Epoch 90/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8472 - auc: 0.9520 - loss: 0.2984 - precision: 0.8235 - recall: 0.8485
Epoch 91/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8981 - auc: 0.9643 - loss: 0.2517 - precision: 0.8738 - recall: 0.9091
Epoch 92/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9028 - auc: 0.9641 - loss: 0.2484 - precision: 0.8980 - recall: 0.8889
Epoch 93/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - auc: 0.9603 - loss: 0.2605 - precision: 0.8866 - recall: 0.8687
Epoch 94/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - auc: 0.9644 - loss: 0.2427 - precision: 0.9032 - recall: 0.8485
Epoch 95/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9120 - auc: 0.9663 - loss: 0.2300 - precision: 0.9167 - recall: 0.8889
Epoch 96/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - auc: 0.9670 - loss: 0.2299 - precision: 0.9091 - recall: 0.9091
Epoch 97/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8981 - auc: 0.9671 - loss: 0.2309 - precision: 0.8889 - recall: 0.8889
Epoch 98/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8935 - auc: 0.9687 - loss: 0.2251 - precision: 0.8800 - recall: 0.8889
Epoch 99/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8981 - auc: 0.9687 - loss: 0.2237 - precision: 0.8889 - recall: 0.8889
Epoch 100/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9028 - auc: 0.9706 - loss: 0.2158 - precision: 0.8980 - recall: 0.8889
Epochs run: 100

    accuracy       auc      loss  precision    recall
95  0.916667  0.966977  0.229928   0.909091  0.909091
96  0.898148  0.967107  0.230878   0.888889  0.888889
97  0.893519  0.968747  0.225070   0.880000  0.888889
98  0.898148  0.968661  0.223657   0.888889  0.888889
99  0.902778  0.970560  0.215785   0.897959  0.888889