In [20]:
import tensorflow as tf

In [21]:
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.utils.class_weight import compute_class_weight

In [22]:
df = pd.read_csv("Heart_disease_statlog.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0

In [23]:
df=df.dropna()
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(df.drop("target", axis=1), df["target"], test_size=0.2, random_state=42)

In [26]:
tf.keras.utils.set_random_seed(42)

nn_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.Dense(16, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

In [29]:

nn_model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
    loss="mean_squared_error",
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.AUC(name="auc")
    ]
)

history = nn_model.fit(
    X_train,
    y_train,
    epochs=30,
    #class_weight=class_weights,
)

history_df = pd.DataFrame(history.history)
print("Epochs run:", len(history_df))
history_df.tail()

Epoch 1/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.4583 - auc: 0.4882 - loss: 0.5418 - precision: 0.4583 - recall: 1.0000
Epoch 2/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 3/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 4/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 5/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 6/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 7/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 8/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 9/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 10/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 11/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 12/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 13/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 14/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 15/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 16/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 17/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 18/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 19/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 20/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 21/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 22/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 23/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 24/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 25/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 26/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 27/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 28/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 29/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epoch 30/30
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4583 - auc: 0.5000 - loss: 0.5417 - precision: 0.4583 - recall: 1.0000
Epochs run: 30

    accuracy  auc      loss  precision  recall
25  0.458333  0.5  0.541667   0.458333     1.0
26  0.458333  0.5  0.541667   0.458333     1.0
27  0.458333  0.5  0.541667   0.458333     1.0
28  0.458333  0.5  0.541667   0.458333     1.0
29  0.458333  0.5  0.541667   0.458333     1.0